Dry-run mode
hamidra/uniques-campaign-runner pull request #14
Opened 2022-02-07 18:19 UTC by jsidorenko

Closes #7

2022-02-08 00:43 UTC, hamidra commented
Some other stuff that we can consider as part of dryRun:
-Can you also check if we can use dryRun [RPC](https://polkadot.js.org/docs/substrate/rpc) to dryRun the chain txs as well when that RPC exists by the chain, .
api.rpc.system.dryRun

-We can verify if a metadata is specified the corresponding media files are available in the instance.metadata.imageFolder per each minting row (e.x. if it mints rows from 1-10 and the image.metadat.extension is png  1.png ... 10.png should be available in the specified directory)

2022-02-11 19:36 UTC, hamidra requested changes

2022-02-11 19:36 UTC, hamidra commented on src/index.js
> +    console.error(err?.message ?? err);
This is nice, but I was thinking for any error that is not related to the workflow and is not a user error, we want to print the whole trace for debugging?! generally this should not happen unless we have a bug or mishandling the errors.

2022-02-11 19:36 UTC, hamidra commented on src/workflow/balanceTransfer.js
> +  if (!dryRun) console.log(call.toHuman());
This is probably some leftover from my debuggings. can be deleted.

2022-02-11 19:36 UTC, hamidra commented on src/workflow/metadata.js
> +  if (!dryRun) console.log(call.toHuman());
This can be deleted.

2022-02-11 19:36 UTC, hamidra commented on src/workflow/metadata.js
> +  await setClassMetadata(connection, classId, metaCid, dryRun);
Shouldn't this be reverted since we are not doing tx dryRun anymore?!

2022-02-11 19:51 UTC, jsidorenko commented on src/index.js
> +    console.error(err?.message ?? err);
Got it, I'll revert it then

2022-02-11 19:54 UTC, jsidorenko commented on src/workflow/metadata.js
> +  await setClassMetadata(connection, classId, metaCid, dryRun);
Will do

2022-02-11 20:11 UTC, hamidra approved these changes

2022-02-14 12:45 UTC, merged